calculator: main.o addition.o division.o print_res.o
	g++ main.o addition.o division.o print_res.o -o calculator
        
main.o: main.cpp
	g++ -c main.cpp
	 
addition.o: addition.cpp
	g++ -c addition.cpp
	
division.o: division.cpp
	g++ -c division.cpp
	
print_res.o: print_res.cpp
	g++ -c print_res.cpp 
	
